### ISSUE TITLE
Values with spaces are truncated

### ISSUE THREAD

**Issue by omercnet** [graylog-labs/graylog-plugin-cef#12]
The regex is looking for two groups of `\S+`, it should be `(\w+)=(.*?(?=\s\w+=|$))` to catch values with spaces in them (which is annoyingly common)

I'm not sure why (I hate Java) but I can't get this pattern to work, would appreciate your help fixing this

**Comment by joschi** [comment]
Closed via 38d8d8e80eb91be4b1de03214b7bdcf150453f0c.
