### ISSUE TITLE
CEF Severity supports both Strings and Integers

### ISSUE THREAD

**Issue by BenjaminLSmith** [graylog-labs/graylog-plugin-cef#18]
We have several ArcSight smart connectors processing/outputting messages in CEF format that are failing when using the parse_cef() function. The ArcSight Smart connector is already converting the CEF Severity to the "Low", "High"...etc. equivalent instead of the integer. Example:

CEF:0|Check Point|Security Gateway/Management|1.0|ctl|ctl|Low| ....

java.lang.NumberFormatException: For input string: "Low"

As of May 16th, 2016, Common Event Format v23 allows Severity to be a string value Low, Medium, High, or Very-High, or the integer value of 0-10. Would it be possible to get support for these string values?

**Comment by SonofLiberty90** [comment]
@BenjaminLSmith Before devs fix this in the official branch, please check my forked repo:
https://github.com/SonofLiberty90/graylog-plugin-cef

I fixed some things there including string severity field parsing.
